version: '3.8'

services:
  postgres_user_api:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgres/data 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userApi 
  user_api:
    container_name: user_api
    build: ../user-api/.
    restart: always
    depends_on:
      - postgres_user_api
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/userApi?schema=public"
  postgres_news_api:
    container_name: postgresNews
    image: postgres:15
    ports:
      - "5433:5432"
    volumes: 
      - db_news:/var/lib/postgres/data 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsApi
  news_api:
    container_name: news_api
    build: ../news-api/.
    restart: always
    depends_on:
      - postgres_news_api
    ports:
      - 8081:8081
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgresNews:5432/newsApi?schema=public"
  news-manager:
    container_name: news_manager
    build: ../news-manager/.
    restart: always
    depends_on:
      - postgres_user_api
      - user_api
    ports:
      - 8082:8082
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/userApi?schema=public"
  news-client-email:
    container_name: news_client_email
    build: ../news-client-email/.
    restart: always
    depends_on:
      - news-manager
    ports:
      - 9090:9090
    env_file:
      - .env
  news-client-telegram:
    container_name: news-client-telegram
    build: ../news-client-telegram/.
    restart: always
    depends_on:
      - news-manager
    ports:
      - 9092:9092
    env_file:
      - .env
  news-client-discord:
    container_name: news-client-discord
    build: ../news-client-discord/.
    restart: always
    depends_on:
      - news-manager
    ports:
      - 9091:9091
    env_file:
      - .env
volumes:
  db:
  db_news:
